### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Freeaqingme** [acomagu/bufpipe#3]
Hi,

Currently the repository does not contain any license. Would you mind adding one?

Personally, I'd prefer MIT, 2-clause BSD or Apache license. But of course, the choice is yours :)

Thanks!

**Comment by acomagu** [comment]
@Freeaqingme I added LICENSE file, as MIT.
I'm really sorry for late action. Hope to help you!

**Comment by Freeaqingme** [comment]
@acomagu that's perfect, thank you!
