### ISSUE TITLE
Is there a new release planned?

### ISSUE THREAD

**Issue by tjamet** [acomagu/bufpipe#7]
Hi!

Thanks for this library, and thanks for adding the license requested by #3 

Following this added license, I notice that the currently latest version (v1.0.3) does not contain the LICENSE file.
This means that strictly speaking, version 1.0.3 cannot be imported in projects under the MIT license or similar.

Would it be possible to plan a new release so we can fix this legal gap?

Thank you

**Comment by acomagu** [comment]
I released [v1.0.4](https://github.com/acomagu/bufpipe/releases/tag/v1.0.4) now. I'm sorry for late.
